name: FileZilla Compatibility Workflow
on:
  push:
    branches: 
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_PAT }}
      - name: Find and Replace (href)
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "href=\"/"
          replace: "href=\"/~sk/"
          regex: false
      - name: Find and Replace (src)
        uses: jacobtomlinson/gha-find-replace@v3
        with:
            find: "src=\"/"
            replace: "src=\"/~sk/"
            regex: false
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Automated Change
